### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by itasahobby** [itasahobby/linkManager#1]
- [ ] Create a graphical interface to add,delete and modify the links and groups.
- [ ]  Add commands  to add,delete and modify the links and groups manually if desired.
- [ ] Create logs of when each link was opened and let configure how they are created.
